spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        session_factory:
          statement_inspector: com.efaturaai.core.jpa.TenantStatementInspector
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: it

logging:
  level:
    root: INFO
    org.springframework.test.context: INFO

provider:
  soap:
    endpoint: http://localhost:0/ws

security:
  permitAll: true


